sudo: required
language: node_js
node_js:
  - "7"
services:
  - postgresql
before_install:
  - npm install -g node-gyp webpack
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - webpack --progress -p
env:
  - verbose=true travis=true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5